import 'package:flutter/material.dart';

/// Simple in-memory translator for three supported languages.
///
/// Usage:
/// ```dart
/// final text = LanguageConverter.translate('home', const Locale('vi'));
/// ```
class LanguageConverter {
  static const Map<String, Map<String, String>> _localizedValues = {
    'en': {
      'darkMode': 'Dark Mode',
      'language': 'Language',
      'system': 'System',
      'light': 'Light',
      'dark': 'Dark',
      'english': 'English',
      'vietnamese': 'Vietnamese',
      'chinese': 'Chinese',
      'home': 'Home',
      'detail': 'Detail',
      'settings': 'Settings',
      'searchList': 'Search List',
      'retest': 'Retest',
      'dataCloud': 'DataCloud',
      'qrScan': 'QR Scan',
      'search': 'Search',
      'confirmDelete': 'Confirm Delete',
      'delete': 'Delete',
      'download': 'Download',
      'cancel': 'Cancel',
      'enterKeyword': 'Enter keyword',
      'noItemsFound': 'No items found',
      'uploadFile': 'Upload File',
      'newFolder': 'New Folder',
      'create': 'Create',
      'selectStatus': 'Select Status',
      'results': 'Results',
      'importPhoto': 'Import Photo',
      'submit': 'Submit',
      'serialNumber': 'SerialNumber',
      'retestSuccess': 'Retest submitted successfully!',
      'back': 'Back to previous folder',
    },
    'vi': {
      'darkMode': 'Chế độ tối',
      'language': 'Ngôn ngữ',
      'system': 'Hệ thống',
      'light': 'Sáng',
      'dark': 'Tối',
      'english': 'Tiếng Anh',
      'vietnamese': 'Tiếng Việt',
      'chinese': 'Tiếng Trung',
      'home': 'Trang chủ',
      'detail': 'Chi tiết',
      'settings': 'Cài đặt',
      'searchList': 'Danh sách tìm kiếm',
      'retest': 'Kiểm tra lại',
      'dataCloud': 'DataCloud',
      'qrScan': 'Quét mã QR',
      'search': 'Tìm kiếm',
      'confirmDelete': 'Xác nhận xóa',
      'delete': 'Xóa',
      'download': 'Tải xuống',
      'cancel': 'Hủy',
      'enterKeyword': 'Nhập từ khóa',
      'noItemsFound': 'Không tìm thấy mục nào',
      'uploadFile': 'Tải tệp lên',
      'newFolder': 'Thư mục mới',
      'create': 'Tạo',
      'selectStatus': 'Chọn trạng thái',
      'results': 'Kết quả',
      'importPhoto': 'Chọn ảnh',
      'submit': 'Gửi',
      'serialNumber': 'SerialNumber',
      'retestSuccess': 'Gửi kết quả thành công!',
      'back': 'Trở lại thư mục trước',
    },
    'zh': {
      'darkMode': '暗黑模式',
      'language': '语言',
      'system': '系统',
      'light': '亮',
      'dark': '暗',
      'english': '英语',
      'vietnamese': '越南语',
      'chinese': '中文',
      'home': '首页',
      'detail': '详细',
      'settings': '设置',
      'searchList': '搜索列表',
      'retest': '重新测试',
      'dataCloud': '数据云',
      'qrScan': '扫描二维码',
      'search': '搜索',
      'confirmDelete': '确认删除',
      'delete': '删除',
      'download': '下载',
      'cancel': '取消',
      'enterKeyword': '输入关键字',
      'noItemsFound': '未找到项目',
      'uploadFile': '上传文件',
      'newFolder': '新建文件夹',
      'create': '创建',
      'selectStatus': '选择状态',
      'results': '结果',
      'importPhoto': '导入图片',
      'submit': '提交',
      'serialNumber': '序列号',
      'retestSuccess': '重测提交成功!',
      'back': '返回上一级文件夹',
    }
  };

  static String translate(String key, Locale locale) {
    return _localizedValues[locale.languageCode]?[key] ?? key;
  }
}

